name: lychee_nft_app
description: 钜园农业荔枝NFT预售平台移动应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI组件
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  
  # 网络请求
  dio: ^5.4.0
  http: ^1.1.2
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # 导航
  go_router: ^13.0.0
  
  # 工具类
  intl: ^0.19.0
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  qr_flutter: ^4.1.0
  
  # Web3
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # 如果有本地资源文件，可以在这里添加
  # assets:
  #   - images/
  #   - icons/

  fonts:
    - family: PingFang
      fonts:
        - asset: fonts/PingFang.ttf


